devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),  # подключаем документ по пути, делаем главную страницу index.html
    path('', include('users.urls')),  # подключаем пути проекта users
]

# Мы можем сделать что пути будут добавляться только в тот момент, когда мы работаем в режиме разработки.
if settings.DEBUG: # Если в режиме разработки, то у нас будет использоваться urlpatterns что бы картинки отображались корректно. Когда сайт выкладывать на продакшен, когда он готовый, на хостингах это реализуется по другому. Если выложили на хостинг данная настройка отрабатывать уже не будет. Пути настраиваютя на самом хостинге.
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Объединяем settings.MEDIA_URL с document_root=settings.MEDIA_ROOT Что бы у нас корректно отображались изображения.

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.user_profile, name='user_profile'),
    path('account/', views.user_account, name='account'), # аккаунт

    path('login/', views.login_user, name='login'), # авторизация
    path('logout/', views.logout_user, name='logout'), # выйти
    path('register/', views.register_user, name='register'), # регистрация

    path('edit-account/', views.edit_account, name='edit-account'), # редактирования пользователя
    path('create-skill/', views.create_skill, name='create-skill'), # добавление навыков
    path('update-skill/<str:pk>/', views.update_skill, name='update-skill'), # редактирование навыков
    path('delete-skill/<str:pk>/', views.delete_skill, name='delete-skill'), # редактирование навыков

    path('inbox/', views.inbox, name='inbox'), # редактирование навыков
    path('message/<str:pk>/', views.view_message, name='message'), # для страницы отдельного сообщения
    path('create-message/<str:pk>/', views.create_message, name='create-message'), # для страницы отдельного сообщения
]

projects/models.py
from django.db import models
from users.models import Profile

class Project(models.Model):
    """Работа с проектами"""
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200) # Название самого какого то проекта
    description = models.TextField(null=True, blank=True) # Поле по больше(Пустое поле, по умолчанию null)
    featured_image = models.ImageField(null=True, blank=True, upload_to='projects/%Y/%m/%d/', default='default.jpg') # Поле для изображения, поле будет заполняться динамически. upload_to - указывает по какому пути будет загружаться изображение. default='default.jpg' не указываем путь к папке, значит она должна лежать в медиа.
    # В БД будет храниться ссылка на эту картинку.(/%Y/%m/%d/ - подстановочный шаблон(/%Y - создастся папка 2023 года, /%m - март, /%d - день в конце / после слеша будет имя изображения.)) И если не загрузили ни какое значение, напишем default='' и подставим какую-то картинку.
    demo_link = models.CharField(max_length=2000, null=True, blank=True) # будет два перехода
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True) # для подсчёта кол-ва процентов
    vote_ratio = models.IntegerField(default=0, null=True, blank=True) # для подсчёта кол-ва
    created = models.DateTimeField(auto_now_add=True)  # Дата создания какого-то проекта.

    def __str__(self):
        """Заголовок проекта"""
        return self.title

    # Класс Meta отвечает за дополнительные настройки. (Пример способ сортировки)
    class Meta:
        """Порядок вывода элементов"""
        ordering = ['-vote_total'] # Привяжемся к положительным либо отрицательным отзывам

    def reviewers(self): # Что бы элементы считались
        queryset = self.review_set.all().values_list('owner__id', flat=True) # через self.review_set.all() будем брать все данные, список значений(id владельца)
        return queryset

    def get_vote_count(self):
        reviews = self.review_set.all()
        up_votes = reviews.filter(value='up').count() # value='up' - как ключ, количество отзывов положительных
        total_votes = reviews.count() # общее количество отзывов.
        ratio = (up_votes / total_votes) * 100 # общий рейтинг положительных отзывов
        self.vote_total = total_votes # сохранили в поле vote_total общее кол-во голосов
        self.vote_ratio = ratio # сохранили в поле vote_ratio общий рейтинг положительных отзывов
        self.save() # Сохранил текущий экземпляр.


class Tag(models.Model):
    """Работа с тегами"""
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True) # Дата создания тега

    def __str__(self):
        """Имя тега"""
        return self.name


class Review(models.Model):
    """Работа с комментариями"""
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    ) # Будет два варианта положительный, либо отрицательный отзыв.
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True) # владелец отзыва. null=True - поле владельца может быть пустым и писать комментарий может любой пользователь и не зарегистрированный.
    project = models.ForeignKey(Project, on_delete=models.CASCADE) # делать поле пустым не будем, пот-то отзывы делаем по какому-то проекту. Обязательно поле проекты должно быть заполнено.
    body = models.TextField(null=True, blank=True) # тело самого отзыва.
    value = models.CharField(max_length=200, choices=VOTE_TYPE) # а атрибут choices добавим VOTE_TYPE - будем выбирать один из элементов VOTE_TYPE. Из выпадающего списка будет выбираться одно из значений. max_length=200 - для текста выпадающего списка.
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Будем видеть положительный или отрицательный отзыв"""
        return self.value

    class Meta:
        """Уникальный отзыв от одного имени."""
        unique_together = [['owner', 'project']] # unique_together - специальное имя переменной, пара уникальных элементов. Что бы пользователь был уникальный для одного проекта.

users/models.py
from django.db import models
from django.contrib.auth.models import User  # Модель самого пользователя есть в самом django


class Profile(models.Model):
    """Профиль пользователя"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)  # Один профиль пользователя может быть связан с одним зарегистрированным пользователем, у которого могут быть проекты и т.д. Что бы одна регистрационная учётка соответствовала одному профилю пользователя.
    # В админке у нас есть пользователи, но нам надо как то связать с профилем пользователя, как бы пользователь это одно, а профиль пользователя, что бы его можно было какими-то данными наполнять его профиль. У пользователя может быть свой профиль, в котором могут быть более расширенные данные.
    # Когда мы пользователя зарегистрировали он попадает в общую модель пользователей, которая есть уже в django, и что бы профиль пользователя, его личные данные могли связываться только с этим одним полем.
    # null=True, blank=True что бы если пользователь создан, учётная запись могла быть пустой.
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)  # что бы у него проходила валидация от самого django
    username = models.CharField(max_length=200, blank=True, null=True)
    short_info = models.CharField(max_length=200, blank=True, null=True)  # краткое описание
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(blank=True, null=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Имя пользователя"""
        return f'{self.username}'


class Skill(models.Model):
    """Модель, отвечающая за навыки пользователя"""
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)  # Владелец скилов.
    name = models.CharField(max_length=200, blank=True, null=True)  # имя самого навыка
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Имя навыка"""
        return f'{self.name}'


class Message(models.Model):
    """Для отправки сообщения"""
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True) # отправитель
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='messages') # получатель, related_name - имя по кот-му мы сможем обратиться к данному полю, если какое-то поле по внешнему ключу мы хотим получать доступ, мы к нему не добавляли _set, в место этого мы можем обратиться по этому имени.
    name = models.CharField(max_length=200, null=True, blank=True) # имя пользователя кот-й прислал сообщение.
    email = models.EmailField(max_length=200, null=True, blank=True) # работает как CharField, только валидация будет на ввод email, что бы была @ и один символ после собачки.
    subject = models.CharField(max_length=200, null=True, blank=True) # тема письма
    body = models.TextField() # тело сообщения, поле обязательное для заполнения
    is_read = models.BooleanField(default=False, null=True) # нужно как-то отслеживать сообщение прочитано или нет, есть два состояния, либо прочитано, лио нет. По умолчанию не прочитанное сообщение. null=True - и уже программно будет, что сообщение прочитано.
    created = models.DateTimeField(auto_now_add=True) # дата создания этого сообщения

    def __str__(self):
        return f'{self.subject}'

    # Надо что бы в Админке в какой-то последовательности выводились поля.
    class Meta:
        """Сортировка полей"""
        ordering = ['is_read', '-created'] # Сначала прочитанные или нет, что бы непрочитанные были вверху. По дате создания.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message
from django.forms import ModelForm # что бы данные брались из нашей модели


class MessageForm(ModelForm):
    """Для отправки сообщений"""
    class Meta:
        """Вывод полей"""
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        """Инициализатор будет использовать любые элементы из родительского элемента, через наследование родительского класса."""
        super().__init__(*args, **kwargs)  # наследуемся от ModelForm
        # .widget.attrs.update - виджеты, атрибуты, обновить(в виде словаря передать любые атрибуты которые мы хотим)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class SkillForm(ModelForm):
    """Для добавления навыков"""
    class Meta:
        """Вывод полей с их названиями"""
        model = Skill
        fields = '__all__' # Можем взять из модели все поля
        exclude = ['owner'] # Исключаем поля которые нам не нужны

    def __init__(self, *args, **kwargs):
        """Инициализатор будет использовать любые элементы из родительского элемента, через наследование родительского класса."""
        super().__init__(*args, **kwargs)  # наследуемся от ModelForm
        # .widget.attrs.update - виджеты, атрибуты, обновить(в виде словаря передать любые атрибуты которые мы хотим)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class ProfileForm(ModelForm):
    """Редактирования пользователя """
    class Meta:
        """Вывод полей с их названиями"""
        model = Profile # Данные будем брать из модели Profile
        fields = ['name', 'email', 'username',
                  'bio', 'short_info', 'profile_image',
                  'social_github', 'social_youtube',
                  'social_website'] # разрешаем редактировать

    def __init__(self, *args, **kwargs):
        """Инициализатор будет использовать любые элементы из родительского элемента, через наследование родительского класса."""
        super().__init__(*args, **kwargs)  # наследуемся от ModelForm
        # .widget.attrs.update - виджеты, атрибуты, обновить(в виде словаря передать любые атрибуты которые мы хотим)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class CustomUserCreationForm(UserCreationForm):
    """Регистрации пользователя"""
    class Meta:
        """Вывод полей с их названиями"""
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name'
        }

    def __init__(self, *args, **kwargs):
        """Инициализатор будет использовать любые элементы из родительского элемента, через наследование родительского класса."""
        super().__init__(*args, **kwargs)  # наследуемся от ModelForm
        # .widget.attrs.update - виджеты, атрибуты, обновить(в виде словаря передать любые атрибуты которые мы хотим)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/templates/users/account.html
{% extends 'projects/base.html' %}
{% block content %}

<!-- Main Section -->
<main class="settingsPage profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
                        <img class="avatar avatar--xl dev__avatar" src="{{ profile.profile_image.url }}"/>
                        <h2 class="dev__name">{{ profile.name }}</h2>
                        <p class="dev__title">{{ profile.short_info }}</p>
                        <ul class="dev__social">
                            {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="fa fa-github-square"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_youtube %}
                            <li>
                                <a title="Youtube" href="{{ profile.social_youtube }}" target="_blank"><i class="fa fa-youtube"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="fa fa-sitemap"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                        <!-- Сам себе пользователь сообщение отправлять не должен -->
                        {% if request.user.profile.id != profile.id %} <!-- Если находимся не под своей учётной запись, то только тогда будет активна Send Message. -->
                        <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">
                        {{ profile.bio }}
                    </p>
                </div>
                <div class="settings">
                    <h3 class="settings__title">Skills</h3>
                    <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
                </div>

                <table class="settings__table">
                    {% for skill in skills %}
                    <tr>
                        <td class="settings__tableInfo">
                            <h4>{{ skill.name }}</h4>
                            <p>
                                {{ skill.description }}
                            </p>
                        </td>
                        <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}"><i class="im im-x-mark-circle-o"></i>
                                Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>

                <div class="settings">
                    <h3 class="settings__title">Projects</h3>
                    <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create_project' %}"><i class="im im-plus"></i> Add Project</a>
                </div>

                <table class="settings__table">
                    {% for project in projects %}
                    <tr>
                        <td class="settings__thumbnail">
                            <a href="{% url 'project' project.id %}"><img src="{{ project.featured_image.url }}" alt="Project Thumbnail"/></a>
                        </td>
                        <td class="settings__tableInfo">
                            <a href="{% url 'project' project.id %}">{{ project.title }}</a>
                            <p>
                                {{ project.description|slice:'120' }}...
                            </p>
                        </td>
                        <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_project' project.id %}"><i class="im im-edit"></i> Edit</a>
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_project' project.id %}"><i class="im im-x-mark-circle-o"></i>
                                Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/delete.html
{% extends 'projects/base.html' %}
{% block content %}

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    <p>Are your sure you want to delete <b>"{{ object }}"</b> ?</p> <!-- тег b делает жирным текст -->
                    <a class="btn btn--sub btn--lg  my-md" href="{% url 'account' %}">&#x2190 Go Back</a>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Delete" />
                </form>
            </div>
        </div>
    </main>

{% endblock %}

users/templates/users/inbox.html
{% extends 'projects/base.html' %}
{% block content %}

<!-- Main Section -->
<main class="inbox my-xl">
    <div class="content-box">
        <h3 class="inbox__title">New Messages(<span>{{ unread_count }}</span>)</h3>
        <ul class="messages">
            {% for message in messages_requests %}
            {% if message.is_read == False %} <!-- Если не прочитанные, то будет жирным выделяться -->
            <li class="message message--unread">
                {% else %}
            <li class="message message">
                {% endif %}
                <a href="{% url 'message' message.id %}">
                    <span class="message__author">{{ message.name }}</span>
                    <span class="message__subject">{{ message.subject }}</span>
                    <span class="message__date">{{ message.created}}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</main>

{% endblock %}

users/templates/users/index.html
{% extends 'projects/base.html' %}
{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <!-- Поиск разработчиков -->
            <div class="hero-section__search">
                <form class="form" action="{% url 'profiles' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Developers </label>
                        <!-- value="{{ search_query }}" - ключ внутри обработчика. -->
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                               value="{{ search_query }}"
                               placeholder="Search by developer name"/> <!-- Для того что бы видеть по какому запросу будут находиться данные - value. -->
                    </div>
                    <input class="btn btn--sub btn--lg" type="submit" value="Search"/>
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">
                {% for profile in profiles%}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'user_profile' profile.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image"/>
                                <div class="dev__meta">
                                    <h3>{{ profile.name }}</h3>
                                    <h5>{{ profile.short_info|slice:'60' }}</h5> <!-- |slice:'60' - шаблон, для отображения нужного кол-ва символов -->
                                </div>
                            </div>
                            <p class="dev__info">
                                {{ profile.bio|slice:'200' }}
                            </p>
                            <div class="dev__skills">
                                {% for skill in profile.skill_set.all|slice:'6' %}
                                <span class="tag tag--pill tag--main">
                    <small>{{ skill }}</small>
                  </span>
                                {% endfor %}
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

</main>
{% endblock %}

users/templates/users/message.html
{% extends 'projects/base.html' %}
{% block content %}
{% load static %}

<!-- Main Section -->
<main class="messagePage my-xl">
    <div class="content-box">
        <div class="message">
            <a class="backButton" href="{% url 'inbox' %}">
                <img src="{% static 'images/left.png' %}" alt="">
            </a>
            <h2 class="message__subject">{{ message.subject }}</h2>
            <a href="{% url 'profiles' %}" class="message__author">{{ message.name }}</a>
            <p class="message__date">{{ message.created }}</p>
            <div class="message__body">
                {{ message.body|linebreaksbr }}
            </div>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/message_form.html
{% extends 'projects/base.html' %}
{% block content %}
{% load static %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user_profile' recipient.id %}"><img src="{% static 'images/left.png' %}" alt="left"></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {% if request.user.is_authenticated == False %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{ form.name.label }}</label>
                    {{ form.name }}
                </div>
                <div class="form__field">
                    <label for="formInput#text">{{ form.email.label }}</label>
                    {{ form.email }}
                </div>
                {% endif %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{ form.subject.label }} </label>
                    {{ form.subject }}
                </div>
                <div class="form__field">
                    <label for="formInput#text">{{ form.body.label }} </label>
                    {{ form.body }}
                </div>

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit"/>
            </form>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/profile.html
{% extends 'projects/base.html' %}
{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}"/>
                        <h2 class="dev__name">{{ profile.name }}</h2>
                        <p class="dev__title">{{ profile.short_info }}</p>
                        <ul class="dev__social">
                            {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="fa fa-github-square"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_youtube %}
                            <li>
                                <a title="Youtube" href="{{ profile.social_youtube }}" target="_blank"><i class="fa fa-youtube"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="fa fa-sitemap"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                        <!-- Сам себе пользователь сообщение отправлять не должен -->
                        {% if request.user.profile.id != profile.id %} <!-- Если находимся не под своей учётной запись, то только тогда будет активна Send Message. -->
                        <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">
                        {{ profile.bio }}
                    </p>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Skills</h3>
                    <div class="devInfo__skills">
                        {% for skill in top_skills %}
                        <div class="devSkill">
                            <h4 class="devSkill__title">{{ skill.name }}</h4>
                            <p class="devSkill__info">
                                {{ skill.description }}
                            </p>
                        </div>
                        {% endfor %}

                        <h3 class="devInfo__subtitle">Other Skills</h3>
                        <div class="devInfo__otherSkills">
                            {% for skill in other_skills %}
                            <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill }}</small>
                </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Projects</h3>
                    <div class="grid grid--two">
                        {% for project in profile.project_set.all %}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url 'project' project.id %}" class="project">
                                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail"/>
                                    <div class="card__body">
                                        <h3 class="project__title">{{ project.title }}</h3>
                                        <p><a class="project__author" href="{% url 'user_profile' project.owner.id %}">By {{ project.owner.name }}</a></p>
                                        <p class="project--rating">
                                            <span style="font-weight: bold;">{{ project.vote_total }}%</span> Postitive
                                            Feedback ({{ project.vote_ratio }} Vote{{ project.vote_ratio|pluralize:'s' }})
                                        </p>
                                        <div class="project__tags">
                                            {% for tag in project.tags.all %}
                                            <span class="tag tag--pill tag--main">
                          <small>{{ tag }}</small>
                        </span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/skill_form.html
{% extends 'projects/base.html' %}
{% block content %}
{% load static %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><img src="{% static 'images/left.png' %}" alt="left"></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock %}